### PR TITLE
Refactor breadcrumbs, errors and code reformatting

### PR DESCRIPTION
**Pull request by yookoala**
**Refactor**
## Description
1. Adapt the new `$page->breadcrumbs` global for breadcrumb.
2. Adapt the new `__()` translation string signature.
3. Quoted some missing translation strings.
4. Adapt the new `$page->addError` as error reporting method.
5. Fix a few code PSR-2 formatting issues.
6. Use `__DIR__` for include statements.

## Motivation and Context
See GibbonEdu/core#696

## How Has This Been Tested?
* Locally

### CODE REVIEW

**Comment by rossdotparker** [comment]
Hi Koala, wow, there are a lot of improvements here. Thanks! I'm going to merge now, will then test, and release.

**Comment by rossdotparker** [comment]
Hi Koala, looks like I should've tested before merging...my mistake! I've found a few issues:

- The $page variable for errors conflicts with $page which was already being used for pagination. I've changed the pagination variable to $page and committed directly.
- The use of $page for errors is placing the error at the top of the page, rather than (in the case below) by the table:

screenshot 2019-03-08 at 1 56 08 pm

Could you look into this second issue for me, and then I can test some more?

One further thing to investigate, if you have time, is any Delete actions, which we are now moving over to modal. This can be done as part of a table refactor (bigger job) or simply by adjusting the link. Once the delete is set to modal, the breadcrumb can be removed from that page.

Thanks!

**Comment by yookoala** [comment]
@rossdotparker: I suggested, a while ago, a no result behavior for table in GibbonEdu/core#686, and @SKuipers has some idea on how to do that better fit the existing code. We'll probably need to wait for that before fixing this issue.

**Comment by rossdotparker** [comment]
Hi Koala, thanks for the heads up. I guess we'll come back to #686 at some point. For now, I've adjusted the code to use the old <div> method for those places where $page was not working. I've tested it, and it looks good. I'm going to release it as v1.3.00. Cheers.

**Pull request merged**
